export const brazilStatesWithTimezones = [
  { label: "America/Rio_Branco", value: "GMT-5" },
  { label: "America/Maceio", value: "GMT-3" },
  { label: "America/Belem", value: "GMT-3" },
  { label: "America/Manaus", value: "GMT-4" },
  { label: "America/Bahia", value: "GMT-3" },
  { label: "America/Fortaleza", value: "GMT-3" },
  { label: "America/Sao_Paulo", value: "GMT-3" },
  { label: "America/Cuiaba", value: "GMT-4" },
  { label: "America/Campo_Grande", value: "GMT-4" },
  { label: "America/Recife", value: "GMT-3" },
  { label: "America/Porto_Velho", value: "GMT-4" },
  { label: "America/Boa_Vista", value: "GMT-4" },
  { label: "America/Araguaina", value: "GMT-3" },
];
