export const STRIPE_PRICE_IDS = {
  basic: process.env.NEXT_PUBLIC_STRIPE_PRICE_BASIC!,
  ai100: process.env.NEXT_PUBLIC_STRIPE_PRICE_AI_100!,
  ai200: process.env.NEXT_PUBLIC_STRIPE_PRICE_AI_200!,
  ai300: process.env.NEXT_PUBLIC_STRIPE_PRICE_AI_300!,
  addCalendar: process.env.NEXT_PUBLIC_STRIPE_PRICE_ADD_CALENDAR!,
  addAi: process.env.NEXT_PUBLIC_STRIPE_PRICE_ADD_AI!,
};

// Remover 'as const' para permitir mutabilidade
export const PLANS = [
  {
    id: "basic",
    name: "Agenda Base",
    description: "Agendamento simples sem IA",
    price: "R$ 60",
    period: "/mês",
    priceId: STRIPE_PRICE_IDS.basic,
    planType: "basic" as const,
    features: [
      "Agendamento manual",
      "3 Calendários",
      "Cadastro de clientes manual",
      "Histórico de serviços",
      "Suporte via email",
      "Demais funções básicas",
    ],
    isBasic: true,
  },
  {
    id: "ai100",
    name: "100 Atendimentos IA",
    description: "Ideal para pequenos negócios",
    price: "R$ 190",
    period: "/mês",
    priceId: STRIPE_PRICE_IDS.ai100,
    planType: "ai100" as const,
    features: [
      "100 atendimentos mensais",
      "Reset a cada 24 horas",
      "Suporte via Whatsapp",
      "IA com regras customizadas",
      "Atendimento humanizado",
      "Operação IA 24/7",
    ],
  },
  {
    id: "ai200",
    name: "200 Atendimentos IA",
    description: "Para negócios em crescimento",
    price: "R$ 329",
    period: "/mês",
    priceId: STRIPE_PRICE_IDS.ai200,
    planType: "ai200" as const,
    features: [
      "200 atendimentos mensais",
      "Reset a cada 24 horas",
      "Suporte via Whatsapp",
      "IA com regras customizadas",
      "Atendimento humanizado",
      "Operação IA 24/7",
    ],
    recommended: true,
    discount: "10% Off",
  },
  {
    id: "ai300",
    name: "300 Atendimentos IA",
    description: "Para negócios estabelecidos",
    price: "R$ 467",
    period: "/mês",
    priceId: STRIPE_PRICE_IDS.ai300,
    planType: "ai300" as const,
    features: [
      "300 atendimentos mensais",
      "Reset a cada 24 horas",
      "Suporte via Whatsapp",
      "IA com regras customizadas",
      "Atendimento humanizado",
      "Operação IA 24/7",
    ],
    discount: "15% Off",
  },
]; // Remover 'as const'

export const ADDITIONAL_PLANS = [
  {
    id: "add-calendar",
    name: "Calendário Adicional",
    description: "Adicione mais um calendário ao seu plano base",
    price: "R$ 10",
    period: "/mês",
    priceId: STRIPE_PRICE_IDS.addCalendar,
    planType: "addon" as const,
    features: ["+1 calendário extra", "Compatível com plano base", "Faturamento separado", "Cancele quando quiser"],
    addonType: "calendar" as const,
    requiresBasePlan: true,
  },
  {
    id: "add-ai",
    name: "Atendimentos Adicionais",
    description: "Adicione mais atendimentos IA ao seu plano",
    price: "R$ 25",
    period: " (Único)",
    priceId: STRIPE_PRICE_IDS.addAi,
    planType: "addon" as const,
    features: ["+10 atendimentos IA", "Compatível com planos IA", "Faturamento separado", "Cancele quando quiser"],
    addonType: "ai" as const,
    requiresAiPlan: true,
  },
]; // Remover 'as const'

export const PRICING_TEXTS = {
  title: "Escolha o plano ideal para seu negócio",
  subtitle: "Comece com 7 dias grátis em qualquer plano. Cancele quando quiser.",
  freeTrialText: "🎉 7 dias grátis para testar!",
  trialHighlight: "💡 Teste todas as funcionalidades sem compromisso durante o período gratuito",
  additionalPlansTitle: "Produtos Adicionais",
  additionalPlansSubtitle: "Expanda seu plano com recursos extras",

  // Adicionar propriedades que a landing page espera
  plans: PLANS,
  addons: [
    {
      name: "Calendário Adicional",
      description: "Adicione mais um calendário ao seu plano base",
      price: "R$ 10",
      period: "/Mês",
      comingSoon: false,
    },
    {
      name: "Atendimentos Adicionais",
      description: "Adicione mais atendimentos IA caso necessário para terminar o mês",
      price: "R$ 25",
      period: "(Único)",
      comingSoon: false,
    },
  ],
  includedFeatures: [
    "Agendamento inteligente com IA",
    "Integração com WhatsApp",
    "Calendários ilimitados",
    "Histórico completo de atendimentos",
    "Relatórios detalhados",
    "Suporte prioritário",
    "Backup automático",
    "Personalização avançada",
    "API para integrações",
  ],
};
